site_name: Clarify+
site_description: A lightweight, open-source "decision-aid compiler" that makes any medical PDF or webpage clearer, fairer, and easier to trust.
site_url: https://clarify-plus.github.io/

repo_name: clarify-plus
repo_url: https://github.com/mj-jpgt/clarify-plus

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Components:
    - PDF/HTML Scraper: components/scraper.md
    - EquiCheck: components/equicheck.md
    - NumiCraft: components/numicraft.md
  - API Reference:
    - Scraper API: api/scraper.md
    - EquiCheck API: api/equicheck.md
  - Examples: examples.md
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
